---

- name: check the conf file exists
  stat:
    path: "{{ unbound_config_path }}"
  register: __unbound_conf_file_result

- name: install the main unbound config file
  template:
    src: etc/unbound_global.conf.j2
    dest: "{{ unbound_config_path }}"
    owner: root
    group: root
    mode: "0644"
  when: >
    unbound_global_config is defined
    or not __unbound_conf_file_result.stat.exists
  notify:
    - unbound reload

- name: install the configuration files
  template:
    src: etc/unbound_extra.conf.j2
    dest: "/etc/unbound/unbound.conf.d/{{ item.key }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ unbound_extra_config | dict2items }}"
  notify:
    - unbound reload
