---

- name: 'install the main unbound config file'
  template:
    src: 'etc/unbound_global.conf.j2'
    dest: "{{ _unbound_config_path }}"
    owner: 'root'
    group: "{{ _unbound_root_group }}"
    mode: '0644'
  notify:
    - 'unbound_reload_handler'

- name: 'install the extra configuration files'
  template:
    src: 'etc/unbound_extra.conf.j2'
    dest: "{{ _unbound_config_extra_dir }}/{{ item.name }}.conf"
    owner: 'root'
    group: "{{ _unbound_root_group }}"
    mode: '0644'
  loop: "{{ unbound_extra_config }}"
  notify:
    - 'unbound_reload_handler'
