---

- name: create config sub directory
  file:
    path: /etc/unbound/unbound.conf.d
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: delete some Debian files
  file:
    path: "/etc/unbound/unbound.conf.d/{{ item }}"
    state: absent
  loop:
    - qname-minimisation.conf
    - root-auto-trust-anchor-file.conf

- name: update anchor key
  command: "unbound-anchor -a {{ unbound_root_key }}"
  when: (unbound_default_global_config | combine(unbound_global_config, recursive=True))['auto-trust-anchor-file'] is defined
